### Hypermedia for Actuator Web Endpoints
GET {{host}}/actuator
# Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3UFhvRFRaU0VXVTVTNFc4UytJcTR3PT0iLCJhdXRoIjpbIlJPTEVfRU5EUE9JTlRfQURNSU4iLCJST0xFX0FETUlOIl0sImlhdCI6MTcyODM4Mzk3MywibmJmIjoxNzI4MzgzOTczLCJleHAiOjE3NDM5MzU5NzN9.nEEunZZAiCKa3593qPu31Dr36BU3_Ox5ZhAKyph3JFw # Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### host/jvm info 信息
GET {{host}}/actuator/info
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### 健康检查
GET {{host}}/actuator/health
#Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### prometheus exporter
GET {{host}}/actuator/prometheus
#Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### all metrics
GET {{host}}/actuator/metrics
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### cache 信息
GET {{host}}/actuator/caches
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### cache 信息
GET {{host}}/actuator/caches/5_MINUTES
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### Spring Env 信息
GET {{host}}/actuator/env
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

# Spring Boot Actuator includes the ability to view and configure the log levels of your application at runtime
### Spring loggers 信息
GET {{host}}/actuator/loggers
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### Spring loggers 信息
# /actuator/loggers/{log-name}
GET {{host}}/actuator/loggers/com.github.zzf.learn.app.rpc.http.provider.direct_memory.DirectMemoryController
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### 更改 logger 日志级别
POST {{host}}/actuator/loggers/com.github.zzf.learn.app.rpc.http.provider.direct_memory.DirectMemoryController
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

{
    "configuredLevel": "DEBUG"
}

### 重置 logger 日志级别
POST {{host}}/actuator/loggers/com.github.zzf.learn.app.rpc.http.provider.direct_memory.DirectMemoryController
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

{
  "configuredLevel": null
}

### 线程 dump
GET {{host}}/actuator/threaddump
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### 定时任务
GET {{host}}/actuator/scheduledtasks
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### url mapping
GET {{host}}/actuator/mappings
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

