spring:
  aop:
    proxy-target-class: true
  profiles:
    active: local

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.feng.learn.model
  mapper-locations: classpath:mapper/*.xml

# 和环境相关的配置
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.d.xqcx.com:3306/basic-platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: xq
    password: 123456
