###
GET {{host}}/api/v1/stations?idList=1,2
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

###
GET {{host}}/api/v1/stations/ids
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

###
GET {{host}}/api/v1/stations/3954
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz


###
GET {{host}}/api/users/mobile/15618536513
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

###
GET {{host}}/api/users/mobile/15618536513/token?password=536513
Content-Type: application/json

###
GET {{host}}/api/users/mobile/15618536513
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3UFhvRFRaU0VXVTVTNFc4UytJcTR3PT0iLCJhdXRoIjpbIlJPTEVfRU5EUE9JTlRfQURNSU4iLCJST0xFX0FETUlOIl0sImlhdCI6MTcyODM4Mzk3MywibmJmIjoxNzI4MzgzOTczLCJleHAiOjE3NDM5MzU5NzN9.nEEunZZAiCKa3593qPu31Dr36BU3_Ox5ZhAKyph3JFw # Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

###
GET {{host}}/log/demo
Content-Type: application/json

### 获取日志级别
GET {{host}}/loggers
Content-Type: application/json

### 获取日志级别
GET {{host}}/loggers/com.github.zzf.learn.app.rpc.http.provider.log
Content-Type: application/json

### 设置日志级别
PUT {{host}}/loggers/com.github.zzf.learn.app.rpc.http.provider.log
Content-Type: application/json

{ "level": "DEBUG" }

### 设置日志级别
PUT {{host}}/loggers/com.github.zzf.learn.app.rpc.http.provider.log
Content-Type: application/json
x-trace-log-enabled: true

{ "level": "info" }
