---
# global config
spring:
  application:
    name: spring-consul-app
  jackson:
    default-property-inclusion: non_null
  config:
    # To change the connection properties of Consul Config either set spring.cloud.consul.host and spring.cloud.consul.port or add the host/port pair to the spring.config.import statement such as, spring.config.import=optional:consul:myhost:8500. The location in the import property has precedence over the host and port propertie.
    # import: 'optional:consul:'
    # Removing the optional: prefix will cause Consul Config to fail if it is unable to connect to Consul
    import: 'optional:consul:'
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        enabled: true
        tags: ['spring-boot-actuator']
        metadata:
          author: zhang.zzf
        # health check
        register-health-check: true
        health-check-path: "/actuator/health" # default
        health-check-interval: 10s
        health-check-timeout: 1s
      config:
        enabled: true # default
        format: key_value
        prefixes: [config] # consul用于存储配置的文件夹根目录名为config
        # sets the folder name used by all applications
        # /config/application/data 中的配置可以配所有服务读取
        default-context: application # default
        profile-separator: '::' # default
        # format: yaml
        # data-key: data # default
        watch:
          enabled: true

# 假设 consul 有以下配置。数字越小，配置优先级越高：
# 1. config/spring-consul-app::dev/data
# 2. config/spring-consul-app/data
# 3. config/application::dev/data
# 4. config/application/data

# 指定 `-Dspring.profiles.active=dev` 加载 1,2,3,4 配置
# 启动没有指定 profile，加载 2,4 配置


logging:
  level:
    root: info
  pattern:
    dateformat: HH:mm:ss
    console: '%d{HH:mm:ss} %-5p [%15.15t] %-40.40logger{39} :[%X{x-trace-id}] %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5p [%15.15t] %-40.40logger{39} :[%X{x-trace-id}] %m%n%wEx'
#
# spring-boot actuator
management:
  endpoints:
    web:
      exposure:
        # https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
        include: 'health,info,env,caches,auditevents,prometheus,threaddump,scheduledtasks,mappings,metrics,loggers'
  endpoint:
    env:
      # For HTTP endpoints, a user is considered to be authorized
      # if they have authenticated and have the roles configured by the endpoint?s roles property.
      # By default, any authenticated user is authorized
      show-values: WHEN_AUTHORIZED
  metrics:
    tags:
      application: ${spring.application.name}
# spring-boot actuator Micrometer Observation Annotations support
# To enable scanning of metrics and tracing annotations like @Timed, @Counted, @MeterTag and @NewSpan annotations,
# you will need to set the management.observations.annotations.enabled property to true
micrometer:
  observations:
    annotations:
      enabled: true
# user authorities
user:
  authority:
    configs:
      15618536513:
        - ROLE_ENDPOINT_ADMIN
        - ROLE_ADMIN
      18121127912:
        - ROLE_ADMIN
      17612156408:
        - ROLE_ADMIN

---
# rpc-http module config
server:
  port: 8080

---
# repo module config
spring:
  datasource:
    hikari:
      iot-card:
        maximum-pool-size: 4
        jdbc-url: jdbc:mysql://localhost:3306/iot_card
        username: root
        password: test
        driver-class-name: com.mysql.cj.jdbc.Driver
      my-db:
        maximum-pool-size: 4
        jdbc-url: jdbc:mysql://localhost:3307/my_db
        username: root
        password: test
        driver-class-name: com.mysql.cj.jdbc.Driver


---
# prod config
spring:
  config:
    activate:
      on-profile: [ prod ]

logging:
  level:
    root: info
  file:
    name: logs/info.log
  logback:
    rollingpolicy:
      max-file-size: 32MB
      total-size-cap: 8192MB
      max-history: 256
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
