###
GET http://localhost:8080/greeting?id=1&content=你好

###
POST http://localhost:8080/greeting?id=1&content=你好

###
PUT http://localhost:8080/greeting?id=1&content=你好

###
HEAD http://localhost:8080/greeting?id=1&content=你好

###
OPTIONS http://localhost:8080/greeting?id=1&content=你好

###
DELETE http://localhost:8080/greeting?id=1&content=你好

###
GET http://localhost:8080/greeting
Content-Type: application/json

{
  "id": 2,
  "content": "GET BODY"
}



# POST 参数覆盖
# 不存在参数覆盖， url 中的参数使用 RequestParam 绑定; body 中的参数使用 RequestBody 绑定
###
# @RequestParam("id") Long id 不会解析 POST body 中的数据
POST http://localhost:8080/greeting?id=1&content=你好
Content-Type: application/json

{
  "id": 2,
  "content": "POST BODY"
}

###
POST http://localhost:8080/greeting/post/map/5?id=1&content=你好
Content-Type: application/json
Cookie: user_id=1; user_name=zhang.zzf

{
"id": 2,
"content": "POST BODY"
}
