spring:
  datasource:
    url: jdbc:mysql://10.0.9.18:3306/

mysql:
  db:
    url: jdbc:mysql://10.0.9.18:3306/

map:
  from:
    # config: '{ 5: "10" }'  # ok # 必须有单引号
    # config: '{ "5": 10 }'  # ok # 必须有单引号
    config: '{ 5: 10 }'  # ok # 必须有单引号
    strMap: '{ "5": "10", "key1": "value1", "key2": "value2"}'

priority-zzf: 'value from application.yaml'

