### 100mb
POST {{host}}/api/direct-memory/
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

{
  "size": 104857600
}

###
GET {{host}}/api/direct-memory/
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz


### clear
POST {{host}}/api/direct-memory/_clear
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz


#netty

###
GET {{host}}/api/netty/direct-memory/info
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

### 100mb
POST {{host}}/api/netty/direct-memory/unpooled
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

{
  "size": 104857600
}

### 100mb
POST {{host}}/api/netty/direct-memory/pooled
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz

{
  "size": 104857600
}

### clear
POST {{host}}/api/netty/direct-memory/_clear
Content-Type: application/json
Authorization: Basic MTU2MTg1MzY1MTM6NTM2NTEz


